<?php
/**
 * Created by PHPro
 *
 * @package      Kariboo
 * @subpackage   Shipping
 * @category     Checkout
 * @author       PHPro (info@phpro.be)
 */
/**
 * Import the api with or without key in header.
 */
?>
<?php if (Mage::getStoreConfig('carriers/kariboo/google_maps_api') != ""): ?>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=<?php echo Mage::getStoreConfig('carriers/kariboo/google_maps_api') ?>&sensor=false&v=3.17&sensor=false&libraries=geometry"
        type="text/javascript"></script>
<?php else: ?>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false&v=3.17&sensor=false&libraries=geometry" type="text/javascript"></script>
<?php endif; ?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>kariboo/shipping/infobox.js"></script>